services:
  estoque-db:
    image: postgres:17
    environment:
      POSTGRES_DB: korp_estoque
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - estoque_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d korp_estoque"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  estoque_data: